### ISSUE TITLE
PeriodicReceiver::new() does not work.

### ISSUE THREAD

**Issue by Nekspire** [jkristell/infrared#45]
Hi, i don't understand why your crate doesn't work with STM32H7xx-hal, which i'm using.
Does your crate support only F1 family ? 

`type annotations needed for `infrared::hal::PeriodicReceiver<SM, stm32h7xx_hal::gpio::gpioa::PA0<stm32h7xx_hal::gpio::Input<stm32h7xx_hal::gpio::Floating>>>`

cannot infer type for type parameter `SM`rustc(E0282)
main.rs(86, 9): consider giving `receiver` the explicit type `infrared::hal::PeriodicReceiver<SM, stm32h7xx_hal::gpio::gpioa::PA0<stm32h7xx_hal::gpio::Input<stm32h7xx_hal::gpio::Floating>>>`, where the type parameter `SM` is specified
main.rs(86, 20): cannot infer type for type parameter `SM`
type annotations needed for `infrared::hal::PeriodicReceiver<SM, stm32h7xx_hal::gpio::gpioa::PA0<stm32h7xx_hal::gpio::Input<stm32h7xx_hal::gpio::Floating>>>`
cannot infer type for type parameter `SM`rustc(E0282)
main.rs(86, 9): consider giving `receiver` the explicit type `infrared::hal::PeriodicReceiver<SM, stm32h7xx_hal::gpio::gpioa::PA0<stm32h7xx_hal::gpio::Input<stm32h7xx_hal::gpio::Floating>>>`, where the type parameter `SM` is specified`

**Comment by jkristell** [comment]
Try specify the Protocol you want to decode as a type parameter instead of `SM`.
```
use infrared::{
    hal::PeriodicReceiver,
    protocols::Nec,
}

...

static mut RECEIVER: Option<PeriodicReceiver<Nec, RecvPin>> = None;

...
```

https://github.com/jkristell/infrared-examples/blob/master/stm32f103-bluepill/examples/receiver.rs

Hope that helps!

**Comment by jkristell** [comment]
You probably want something like:
```
let mut receiver: PeriodicReceiver<Nec, RecvPin> = Receiver::new(pin, SAMPLERATE)
```

**Comment by Nekspire** [comment]
> Try specify the Protocol you want to decode as a type parameter instead of `SM`.
> 
> ```
> use infrared::{
>     hal::PeriodicReceiver,
>     protocols::Nec,
> }
> 
> ...
> 
> static mut RECEIVER: Option<PeriodicReceiver<Nec, RecvPin>> = None;
> 
> ...
> ```
> 
> https://github.com/jkristell/infrared-examples/blob/master/stm32f103-bluepill/examples/receiver.rs
> 
> Hope that helps!

Firstly thanks for reply! Actually i was following this example 1 by 1, but on stm32h7. 
I specified the Protocol as you said. And it didn't work when i declared something like this:
` let mut receiver = PeriodicReceiver::new(ir_pin, SAMPLERATE); `

Finally after changing it, as you mentioned to:
` let mut receiver: PeriodicReceiver<Nec, RecvPin> = PeriodicReceiver::new(ir_pin, SAMPLERATE); `

It did not give me an error. Thanks !

**Comment by jkristell** [comment]
You could also give the parameters to new like:

``` 
let mut receiver = PeriodicReceiver::new<Nec, RecvPin>();
```

No problem, thanks for using my library. Always good to get some feedback. I should probably rename SM to DECODER or PROTOCOL to make it clearer what is missing.

**Comment by Nekspire** [comment]
> You could also give the parameters to new like:
> 
> ```
> let mut receiver = PeriodicReceiver::new<Nec, RecvPin>();
> ```
> 
> No problem, thanks for using my library. Always good to get some feedback. I should probably rename SM to DECODER or PROTOCOL to make it clearer what is missing.

Yeah this solution also works great. I found your library on [https://github.com/rust-embedded/awesome-embedded-rust](url), where are many crates. I needed it to control my audio application. Years ago i have written something like this but in C, and it was working in input capture mode. Does your lib provide an option to do this in that way ?

**Comment by jkristell** [comment]
It doesn't provide any direct support for input capture. But it is on the map. But the embedded-hal needs to gain support for abstracting it in some way. Otherwise it would be tied to a specific chip. Today I don't think any of the stm32 hals support input capture, but I would like try to add it at some point and maybe try to add the embedded hal traits.

**Comment by Nekspire** [comment]
Okay so today i have  made some improvements to my code, but it still does't work :(

` //#![deny(warnings)]
#![no_main]
#![no_std]


use cortex_m::{asm, interrupt::{Mutex, free}};
use cortex_m_rt::entry;
use panic_halt as _;

use stm32h7xx_hal::{
    gpio::{gpioa::PA0, Floating, Input},
    timer::{Event, Timer},
    prelude::*,
    stm32::{interrupt, TIM2},
    serial::Tx,
    pac
};

use core::{
    fmt::Write,
    cell::RefCell,
    sync::atomic::{AtomicU32, Ordering}
};

#[allow(unused_imports)]
use infrared::{
    hal::PeriodicReceiver,
    protocols::Nec,
    remotes::{nec::*, rc5::*},
    Button,
};

static OVERFLOWS: AtomicU32 = AtomicU32::new(0);

static TIMER: Mutex<RefCell<Option<Timer<pac::TIM2>>>> =
    Mutex::new(RefCell::new(None));

static TX: Mutex<RefCell<Option<Tx<pac::USART2>>>> =
    Mutex::new(RefCell::new(None));

// Pin connected to the receiver
type RecvPin = PA0<Input<Floating>>;
// Samplerate
const SAMPLERATE: u32 = 20_000;
// Our Infrared receiver
static mut RECEIVER: Option<PeriodicReceiver<Nec, RecvPin>> = None;

#[entry]
fn main() -> ! {
    let mut cp = cortex_m::Peripherals::take().unwrap();
    let dp = pac::Peripherals::take().unwrap();

    // Constrain and Freeze power
    let pwr = dp.PWR.constrain();
    let pwrcfg = pwr.freeze();

    // Constrain and Freeze clock
    let rcc = dp.RCC.constrain();
    let ccdr = rcc.sys_ck(8.mhz()).freeze(pwrcfg, &dp.SYSCFG);


    let mut gpioa = dp.GPIOA.split(ccdr.peripheral.GPIOA);

    let tx = gpioa.pa2.into_alternate_af7();
    let rx = gpioa.pa3.into_alternate_af7();

    let ir_pin = gpioa.pa0.into_floating_input();

    // Get the delay provider.
    let mut delay = cp.SYST.delay(ccdr.clocks);

    let serial = dp.USART2.serial(
        (tx,rx),
        19_200.bps(),
        ccdr.peripheral.USART2,
        &ccdr.clocks)
        .unwrap();


    let (mut tx, mut rx) = serial.split();

    let mut timer = dp.TIM2.timer(SAMPLERATE.hz(), ccdr.peripheral.TIM2, &ccdr.clocks);
    timer.listen(Event::TimeOut);


    // let mut receiver = PeriodicReceiver::new(ir_pin, SAMPLERATE);
    let receiver: PeriodicReceiver<Nec, RecvPin> = PeriodicReceiver::new(ir_pin,
SAMPLERATE);

    unsafe {
        RECEIVER.replace(receiver);
    }

    free(|cs| {
        TX.borrow(cs).replace(Some(tx))
    });

    cortex_m::interrupt::free(|cs| {
        TIMER.borrow(cs).replace(Some(timer));
    });

    unsafe {
        cp.NVIC.set_priority(interrupt::TIM2, 1);
        pac::NVIC::unmask(interrupt::TIM2);
    }


    loop {
        asm::nop();
    }
}

#[interrupt]
fn TIM2() {
    let receiver = unsafe { RECEIVER.as_mut().unwrap() };
    OVERFLOWS.fetch_add(1, core::sync::atomic::Ordering::SeqCst);

    free(|cs| {
        if let Ok(Some(button)) = receiver.poll_button::<SpecialForMp3>() {
            let mut op = TX.borrow(cs).borrow_mut();
            let tx = op.as_mut().unwrap();
            match button {
                Button::Play_Paus => writeln!(tx,"Play was pressed!").unwrap(),
                Button::Next => writeln!(tx,"Next").unwrap(),
                _ => writeln!(tx,"Button: {:?}", button).unwrap(),
            };
        }

    });

    cortex_m::interrupt::free(|cs| {
        let mut rc = TIMER.borrow(cs).borrow_mut();
        let timer = rc.as_mut().unwrap();
        timer.clear_irq();
    })
} `

I monitored that interrupt is fired correctly, but it never pass the 
` if let Ok(Some(button)) = receiver.poll_button::<SpecialForMp3>() `
while i'm clicking the button. I'm 100 % sure that i have NEC controller because as i mentioned i wrote library for it.

**Comment by Nekspire** [comment]
Sorry i don't know why it placed the code in that dirty way.

**Comment by jkristell** [comment]
If you don't have exactly that remote control, that won't work. Try following the tutorial I wrote: https://jott.se/blog/infrared/

**Comment by Nekspire** [comment]
Okay so i finally made it on bluepill :). I'm using this small ir controller.  [https://shop.techmakers.com.my/image/techmakers/image/cache/data/all_product_images/product-510/IR%20Remote%20control%20(%20Car%20MP3%20)-600x600.jpg](url)    

I don't know why it's started to work only when i set the clocks identically like this in example:
`   
     let clocks = rcc
    .cfgr
    .use_hse(8.mhz())
    .sysclk(48.mhz())
    .pclk1(24.mhz())
    .freeze(&mut flash.acr); 
`

**Comment by jkristell** [comment]
I will try both receive and send with a couple of other chips during the week, but there shouldn't be any issues using other MCUs than the stm32f103 as long as you have a timer running at a known good frequency.

Thanks for all the testing!
