### ISSUE TITLE
How to match CmdEnum when using MultiReceiver?

### ISSUE THREAD

**Issue by riskable** [jkristell/infrared#86]
I got `MultiReceiver` working (in my RTIC-using code) but it doesn't look like there's a way to `match` against the `cmd`...

```rust
if let Ok(cmds) = ir_recv.event_iter(elapsed_us) {
    for cmd in cmds {
        defmt::println!("IR: {:?}", cmd); // TEMP
        match cmd {
            <what do I put here?>
        }
    }
}
```

The problem is that `infrared::receiver::multireceiver` is private, therefore `infrared::receiver::multireceiver::CmdEnum` is also private.  So even if I wanted to do something like:

```rust
match cmd {
    infrared::receiver::multireceiver::CmdEnum::Nec(_) => {},
    (_) => {},
}
```

...I can't.  I'm still pretty new to Rust though so maybe I'm missing something?

**Comment by jkristell** [comment]
That's probably something I overlooked. CmdEnum should be accessible. Will fix it before the next release, that should be any day now. Just needs to find some time to do the release. 

Thanks for testing!

**Comment by jkristell** [comment]
CmdEnum renamed to MultiReceiverCommand and is now exported.

**Comment by riskable** [comment]
Excellent! That works, thanks 👍
